### PR TITLE
Use current soundStream setup method

### PR DESCRIPTION
**Pull request by hamoid**
ofSoundStreamSetup is deprecated. 
Also add setApi() method which I needed to make it work with PulseAudio in Linux.

### CODE REVIEW

**Comment by danomatika** [comment]
Note: ofxPd master is kept up with the current OF *release*, not with with the OF master.

**Comment by hamoid** [comment]
Oops sorry, I should have both master and current release folders to test. Feel free to close, or to merge some day in the future :)

**Comment by danomatika** [comment]
No problem. I usually wait for a release and update all of my adding at once.

**Comment by danomatika** [comment]
Fixed with latest commits.

**Pull request closed without merging**
